# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ###############################################

# Run GitHub's Super Linter against code base #

###############################################



name: GitHub's Super Linter

on: push



jobs:

  run-linters:

    name: GitHub's Super Linter

    runs-on: ubuntu-latest



    steps:

      - name: Check out Git repository

        uses: actions/checkout@master

        

      - name: Run GitHub Super Linter

        uses: github/super-linter@master

        env:

          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_JAVASCRIPT_STANDARD: false

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
